// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoUniversidad.Context;

#nullable disable

namespace ProyectoUniversidad.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20240413050806_Migracion")]
    partial class Migracion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProyectoUniversidad.Models.Cuenta", b =>
                {
                    b.Property<int>("cuenta_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cuenta_id"));

                    b.Property<string>("cuenta_clave")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cuenta_nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("rol_id")
                        .HasColumnType("int");

                    b.HasKey("cuenta_id");

                    b.HasIndex("rol_id");

                    b.ToTable("Cuentas");
                });

            modelBuilder.Entity("ProyectoUniversidad.Models.Estudiante", b =>
                {
                    b.Property<int>("estudiante_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("estudiante_id"));

                    b.Property<int>("carrera_id")
                        .HasColumnType("int");

                    b.Property<int>("cuenta_id")
                        .HasColumnType("int");

                    b.Property<bool>("estudiante_activo")
                        .HasColumnType("bit");

                    b.Property<string>("estudiante_apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estudiante_correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estudiante_documento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("estudiante_fecha_ingreso")
                        .HasColumnType("date");

                    b.Property<decimal>("estudiante_indice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("estudiante_nacionalidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estudiante_nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estudiante_telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("estudiante_trimestre")
                        .HasColumnType("int");

                    b.Property<int>("tipo_documento_id")
                        .HasColumnType("int");

                    b.HasKey("estudiante_id");

                    b.HasIndex("carrera_id");

                    b.HasIndex("cuenta_id");

                    b.HasIndex("tipo_documento_id");

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("ProyectoUniversidad.Models.Profesor", b =>
                {
                    b.Property<int>("profesor_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("profesor_id"));

                    b.Property<int>("id_cuenta")
                        .HasColumnType("int");

                    b.Property<string>("profesor_apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("profesor_documento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("profesor_nombres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tipo_documento_id")
                        .HasColumnType("int");

                    b.HasKey("profesor_id");

                    b.HasIndex("id_cuenta");

                    b.HasIndex("tipo_documento_id");

                    b.ToTable("Profesors");
                });

            modelBuilder.Entity("ProyectoUniversidad.Models.Rol", b =>
                {
                    b.Property<int>("rol_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("rol_id"));

                    b.Property<string>("rol_nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("rol_id");

                    b.ToTable("Rols");
                });

            modelBuilder.Entity("ProyectoUniversidad.Models.Servicio", b =>
                {
                    b.Property<int>("servicio_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("servicio_id"));

                    b.Property<decimal>("servicio_costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("servicio_nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("servicio_id");

                    b.HasIndex("servicio_nombre")
                        .IsUnique();

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("UniversidadAPI.Models.Asignatura", b =>
                {
                    b.Property<int>("asignatura_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("asignatura_id"));

                    b.Property<string>("asignatura_aula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("asignatura_creditos")
                        .HasColumnType("int");

                    b.Property<string>("asignatura_nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("profesor_id")
                        .HasColumnType("int");

                    b.HasKey("asignatura_id");

                    b.HasIndex("profesor_id");

                    b.ToTable("Asignaturas");
                });

            modelBuilder.Entity("UniversidadAPI.Models.Carrera", b =>
                {
                    b.Property<int>("carrera_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("carrera_id"));

                    b.Property<string>("carrera_area")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("carrera_nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("carrera_id");

                    b.HasIndex("carrera_nombre")
                        .IsUnique();

                    b.ToTable("Carreras");
                });

            modelBuilder.Entity("UniversidadAPI.Models.Seleccion", b =>
                {
                    b.Property<int>("seleccion_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("seleccion_id"));

                    b.Property<int>("estudiante_id")
                        .HasColumnType("int");

                    b.Property<int>("seleccion_creditos")
                        .HasColumnType("int");

                    b.Property<int>("seleccion_estado")
                        .HasColumnType("int");

                    b.Property<decimal>("seleccion_indice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("seleccion_trimestre")
                        .HasColumnType("int");

                    b.HasKey("seleccion_id");

                    b.HasIndex("estudiante_id");

                    b.ToTable("Seleccions");
                });

            modelBuilder.Entity("UniversidadAPI.Models.Tipo_documento", b =>
                {
                    b.Property<int>("tipo_documento_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("tipo_documento_id"));

                    b.Property<string>("tipo_documento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("tipo_documento_id");

                    b.ToTable("Tipo_documentos");
                });

            modelBuilder.Entity("ProyectoUniversidad.Models.Cuenta", b =>
                {
                    b.HasOne("ProyectoUniversidad.Models.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("rol_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("ProyectoUniversidad.Models.Estudiante", b =>
                {
                    b.HasOne("UniversidadAPI.Models.Carrera", "Carrera")
                        .WithMany()
                        .HasForeignKey("carrera_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoUniversidad.Models.Cuenta", "Cuenta")
                        .WithMany()
                        .HasForeignKey("cuenta_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversidadAPI.Models.Tipo_documento", "Tipo_documento")
                        .WithMany()
                        .HasForeignKey("tipo_documento_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrera");

                    b.Navigation("Cuenta");

                    b.Navigation("Tipo_documento");
                });

            modelBuilder.Entity("ProyectoUniversidad.Models.Profesor", b =>
                {
                    b.HasOne("ProyectoUniversidad.Models.Cuenta", "Cuenta")
                        .WithMany()
                        .HasForeignKey("id_cuenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversidadAPI.Models.Tipo_documento", "Tipo_documento")
                        .WithMany()
                        .HasForeignKey("tipo_documento_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuenta");

                    b.Navigation("Tipo_documento");
                });

            modelBuilder.Entity("UniversidadAPI.Models.Asignatura", b =>
                {
                    b.HasOne("ProyectoUniversidad.Models.Profesor", "Profesor")
                        .WithMany()
                        .HasForeignKey("profesor_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("UniversidadAPI.Models.Seleccion", b =>
                {
                    b.HasOne("ProyectoUniversidad.Models.Estudiante", "Estudiante")
                        .WithMany()
                        .HasForeignKey("estudiante_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estudiante");
                });
#pragma warning restore 612, 618
        }
    }
}
